Этап 1 дипломной работы
KseniaYakovenko/java-plus-graduation pull request #2
Opened 2024-12-25 17:56 UTC by KseniaYakovenko

2024-12-26 07:58 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-12-26 07:58 UTC, LexLippi commented on stats/stats-server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS hits CASCADE;
Вот эту строчку, мы явно не хотим иметь в продакшен-скрипте, чтобы при каждом обновлении все данные перезатирались

2024-12-26 07:58 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/utils/Constants.java
> +    public static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern(timestampPattern);
Советую именовать константы в соответствии с [Java Google Code Style](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names)

2024-12-26 07:58 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/service/StatsServiceImpl.java
> +    public List<HitStatDto> getHits(String start, String end, List<String> uris, Boolean unique) {
Это стоит выполнять в `readOnly`-транзакции --https://stackoverflow.com/questions/44984781/what-are-advantages-of-using-transactionalreadonly-true

2024-12-26 07:58 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/StatClient.java
> +    List<HitStatDto> getStats(@RequestParam(value = "start", required = false, defaultValue = "") String start,
1. в `value` нет необходимости, если оно совпадает с названием переменной
2. `required = false` не требуется, если у нас есть `defaultValue`

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS LIKES_LOCATIONS CASCADE;
вот этого в продакшен-миграции быть не должно

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/service/UserServiceImpl.java
> +    @Transactional
Здесь вроде бы достаточно `readOnly=true` транзакции

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/service/UserServiceImpl.java
> +                    Arrays.asList(adminUsersGetAllParams.ids()), PageRequest.of(adminUsersGetAllParams.from(), adminUsersGetAllParams.size()));
1. `pageRequest` одинаковый можно его вынести в переменную
2. А зачем в ветке `else` мы делаем `.stream().toList()` там метод не `List` возвращает?
3. Теоретически можно переписать в виде тернарника, но это по желанию

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/service/RequestServiceImpl.java
> +    public ParticipationRequestDto create(long userId, long eventId) {
`Transactional`

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/service/LocationServiceImpl.java
> +        if (locationRepository.checkLikeExisting(userId, locationId)) {
Можно инвертировать и избавиться от ветки `else`

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/controller/admin/AdminEventController.java
> +            @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime rangeStart,
Завести константу под `"yyyy-MM-dd HH:mm:ss"`

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/controller/admin/AdminUsersGetAllParams.java
> +        Long[] ids,
Точно хотим с массивом, а не списком работать?

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/controller/priv/PrivateEventController.java
> +            @RequestParam(required = false, defaultValue = "0") Integer from,
`required=false` не нужен, если есть `defaultValue`

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/controller/publ/PublicCompilationController.java
> +    public List<CompilationDto> getAll(@RequestParam(value = "pinned", required = false, defaultValue = "false") Boolean pinned,
`required=false` не нужен

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/controller/publ/PublicEventController.java
> +            @RequestParam(required = false, defaultValue = "false") Boolean onlyAvailable,
`required=false` не нужен

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/controller/publ/PublicEventController.java
> +            @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime rangeEnd,
под формат даты -- константу

2024-12-26 07:58 UTC, LexLippi commented on core/main-service/src/main/java/ru/practicum/controller/publ/PublicEventController.java
> +    private final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
можно добавить `static`, так как это явно константа

2024-12-26 10:56 UTC, KseniaYakovenko commented on stats/stats-server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS hits CASCADE;
спасибо, убрала

2024-12-26 10:57 UTC, KseniaYakovenko commented on core/main-service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS LIKES_LOCATIONS CASCADE;
убрала

2024-12-26 11:01 UTC, KseniaYakovenko commented on stats/stats-server/src/main/java/ru/practicum/utils/Constants.java
> +    public static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern(timestampPattern);
исправила

2024-12-26 11:03 UTC, KseniaYakovenko commented on stats/stats-server/src/main/java/ru/practicum/service/StatsServiceImpl.java
> +    public List<HitStatDto> getHits(String start, String end, List<String> uris, Boolean unique) {
спасибо, добавила

2024-12-26 11:05 UTC, KseniaYakovenko commented on stats/stats-client/src/main/java/ru/practicum/StatClient.java
> +    List<HitStatDto> getStats(@RequestParam(value = "start", required = false, defaultValue = "") String start,
исправила

2024-12-26 11:06 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/service/UserServiceImpl.java
> +    @Transactional
добавила

2024-12-26 11:26 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/service/UserServiceImpl.java
> +                    Arrays.asList(adminUsersGetAllParams.ids()), PageRequest.of(adminUsersGetAllParams.from(), adminUsersGetAllParams.size()));
1. вынесла в переменную
2. это оптимизированный метод stream для collect(Collectors.toList())
3. переписала

2024-12-26 11:27 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/service/RequestServiceImpl.java
> +    public ParticipationRequestDto create(long userId, long eventId) {
добавила

2024-12-26 11:31 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/service/LocationServiceImpl.java
> +        if (locationRepository.checkLikeExisting(userId, locationId)) {
исправила

2024-12-26 11:39 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/controller/admin/AdminEventController.java
> +            @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime rangeStart,
вынесла в константу

2024-12-26 11:42 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/controller/admin/AdminUsersGetAllParams.java
> +        Long[] ids,
заменила на List

2024-12-26 11:43 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/controller/publ/PublicCompilationController.java
> +    public List<CompilationDto> getAll(@RequestParam(value = "pinned", required = false, defaultValue = "false") Boolean pinned,
убрала

2024-12-26 11:45 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/controller/publ/PublicEventController.java
> +            @RequestParam(required = false, defaultValue = "false") Boolean onlyAvailable,
убрала

2024-12-26 11:46 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/controller/publ/PublicEventController.java
> +            @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime rangeEnd,
вынесла в константу

2024-12-26 11:46 UTC, KseniaYakovenko commented on core/main-service/src/main/java/ru/practicum/controller/publ/PublicEventController.java
> +    private final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
добавила

2024-12-27 08:36 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи со следующими частями диплома!

2025-01-09 09:20 UTC, merged